FROM node:alpine
RUN apk --no-cache add openjdk25 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk --no-cache add git
# RUN adduser -h /home/builduser -S builduser
# RUN mkdir -p /var/jenkins_home/
# RUN chown builduser /var/jenkins_home
# USER builduser
# WORKDIR /home/builduser